### ISSUE TITLE
Transformers

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#102]
We have one planned transformer "vector2product" but have not discussed how transformers should function in distr6. I see the following options:

1. An R6 object of class "transformer" that acts like the Adapter and changes the pdf/cdf of a vector distribution by wrapping it in `apply(pdfs,1,product)`
1. A method that creates a new product distribution by taking all the properties of the vector distribution and using them to create the product distribution
1. We don't have a transformer at all but `ProductDistribution` can take as an argument a `VectorDistribution`
1. The transformer takes as inputs the vector `pdf` / `cdf` results and just wraps these in the `apply(...)` method

**Comment by fkiraly** [comment]
When I read `transformer`, I thought this would be a compositor where you apply a function to the random variable's value and consider the distribution of that? I.e., Jacobian and transformation of random variables style.

Regarding the "transformation" you refer to, I think it's vector-to-product distribution? I don't think this needs transformation, especially since the output types of methods (e.g., pdf, or sample) may differ.

In particular, I'd go with half of @berndbischl 's suggestion, and have single samples from a product be row vectors, while single samples from the vector distribution should be column vectors.

**Comment by RaphaelS1** [comment]
Okay!

> In particular, I'd go with half of @berndbischl 's suggestion, and have single samples from a product be row vectors, while single samples from the vector distribution should be column vectors.

This is now implemented, see `VectorDistribution` and `ProductDistribution` for examples
