### ISSUE TITLE
empirical distributions, & should `simulateEmpiricalDistribution` work on non-empirical?

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#148]
The function simulates *without* replacement, hence currently defined (and named) for `Empirical` distributions only. However, we could extend this to all distributions and just have this as a 'simulate without replacement' function

**Comment by fkiraly** [comment]
I've asked myself this question as well - but it makes sense only for distributions that are either mixed or discrete, as for continuous ones this will be simply the same as sampling with replacement.

I agree it makes a lot of sense for empirical distributions, but I'm not sure about all others.

**Comment by RaphaelS1** [comment]
Sure I agree. And just to check I've defined the pmf as:

```R
p(x) = sum(I(x_i = x))/|X|
```
where `|X|` is the length of vector `X = x_1,...,x_n`.

i.e. the proportion of samples at x over the total amount
and the cdf as
```R
p(x) = sum(I(x_i <= x))/|X|
```
i.e. proportion of samples equal to or less than x

**Comment by fkiraly** [comment]
Can you explain how this is related to the question of simulation without replacement?

I've thought about it and think it really makes sense only for discrete distributions.

Regarding the pmf and cdf, this is correct, but only for an empirical sample.
For convenience, I'd store the following as an array:

1st column, the values the distribution takes, in ascending order (without multiplicity); 2nd column, the multiplicity; 3rd column, the value of the cdf at that point.

Then you can use binary search to find the row index corresponding to a real number, thus evaluation of pdf/cdf costs only O(log(samplesize)) rather than O(samplesize), which is much less. Of course you may have to sort it once when it isn't sorted to begin with.
