### ISSUE TITLE
Return type for simulations from multivariate distributions

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#197]
There's currently an inconsistency in how random draws are returned for multivariate distributions. Current set-up:

| | Univariate | Multivariate |
|-|---------- |---|
**Standard**| vector | data.table, rows = draws, cols = corresponding variable
**VectorDist** | data.table, rows = draws, cols = corresponding parameter | ??? |

I would like to find a way that doesn't involve arrays but not sure if that's possible...

**Comment by RaphaelS1** [comment]
The only way I can think of is we return `data.table` where cols are corresponding parameter and rows are draws*variables. e.g. for 2 draws from a bivariate distribution vectorised twice:


| X1 | X2 |
|---|---|
|r111|r211|
|r112|r212|
|r121|r221|
|r122|r222|

where rijk is the kth variable in the jth draw from the ith distribution in the vector

**Comment by fkiraly** [comment]
Can you explain what you mean with "parameters"?

As far as I understand, a `VectorDist` is a (flyweight) representation of a vector of distribution objects, each with parameters of course, but the three indices in the multivariate setting correspond to:
* sample index (nth is nth draw)
* variable index (nth is nth variable)
* vector index (nth is nth distribution)
right?

So do you mean in the `VectorDist` sample case current situation:
row index = sample index
col index = vector index
?

**Comment by fkiraly** [comment]
My suggestion would be:
if a user insists of sampling from a `VectorDist` (not sure why you would do that), the natural return type would be [list of](data.table).

The list index is the vector index, and list elements are as in the (non-vector) distribution case, i.e., tables whwere row index = sample index, col index = variable index.

This should also easily allow to extend the interface so the user can specify a different sample size for each vector index, or `VectorDist`s with different number of variables, since the list can hold data.tables of different row size or column size. Bayesians may want to have this, but I would not recommend implementing this right away sine it seems rare.

**Comment by RaphaelS1** [comment]
> vector index (nth is nth distribution)

right, parameter = distribution

> So do you mean in the VectorDist sample case current situation:
row index = sample index
col index = vector index
?

Yes so:
* VectorDist univariate - row = sample, col = vector
* Non-vectordist multivariate - row = sample, col = variable
* VectorDist multivariate - ???

**Comment by fkiraly** [comment]
I would suggest to change this to my suggestion - the return of `VectorDist$sample` is always a list of `data.table`s. The return of non-vector distributions is always a `data.table`.

**Comment by RaphaelS1** [comment]
Surely an `array` would make more sense? This would be consistent with having to pass an `array` to a vector distribution of multivariate distributions

**Comment by fkiraly** [comment]
>Surely an array would make more sense? This would be consistent with having to pass an array to a vector distribution of multivariate distributions.

Can you explain that, please? What is the situation in which you are passing the 3D array?

My suggestion of a list of dataframes/tables is since the sample index dimension (i in your notation) could be different for diferent vector indices.

**Comment by RaphaelS1** [comment]
> Can you explain that, please? What is the situation in which you are passing the 3D array?

``` r
vd = distr6::VectorDistribution$new(distribution = "Dirichlet",
                                    params = list(list(params = c(2, 2)),
                                                  list(params = c(3, 3))))
x = array(c(0.1,0.2,0.9,0.8,0.6,0.3,0.4,0.7), dim = c(2,2,2))
print(x)
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]  0.1  0.9
#> [2,]  0.2  0.8
#> 
#> , , 2
#> 
#>      [,1] [,2]
#> [1,]  0.6  0.4
#> [2,]  0.3  0.7
vd$pdf(data = x)
#>    Diri1 Diri2
#> 1:  0.54 1.728
#> 2:  0.96 1.323
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fkiraly** [comment]
Ah, thanks, I wanted to understand in which situation you pass/obtain data like that, and it is as an argument to `pdf` and other distribution defining functions, makes sense.

Overall, I think this is a nice solution with which we could be consistent, I agree.

I also think though this is not the "perfect" solution, since the sample size could be different or each distribution, i.e., the max of i differs by the value of k.
As I've said, this is rare, but might come up.

The data struture in this case would be a ragged (or jagged) array, which aren't supported nicely in R so it would introduce dependencies.
The solution where we have lists of 2D arrays is slightly uglier and probably more difficult to handle.

I hence agree with you by virtue of your consistency argument: that is, since we already have one case where a 3D array of this form is passed for a sample of multiple distribution, this should precisely be the return format of sampling from multiple distributions.

**Comment by RaphaelS1** [comment]
> I also think though this is not the "perfect" solution, since the sample size could be different for each distribution, i.e., the max of i differs by the value of k.

This is not possible with the current design as vector distributions assume that the same number of samples are always required from distributions. I think the other case can be considered a sufficient-enough use-case that we don't have to use lists which would be uglier.

> The data struture in this case would be a ragged (or jagged) array, which aren't supported nicely in R so it would introduce dependencies.

Exactly. Although sparse matrices could be implemented through `Matrix` which is a core dependency.

**Comment by fkiraly** [comment]
>This is not possible with the current design as vector distributions assume that the same number of samples are always required from distributions. I think the other case can be considered a sufficient-enough use-case that we don't have to use lists which would be uglier.

I know and that´s why I agree with your suggestion as the most pragmatic one.

>Exactly. Although sparse matrices could be implemented through Matrix which is a core dependency.

Which might be fine for internal use but might make things more difficult in user-facing interfaces,, so I would agree with avoiding it.
