### ISSUE TITLE
Divergent integrals - Exception handling

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#57]
````R
E <- Exponential$new(decorators = ExoticStatistics)
E$cdfAntiDeriv()
````

Problem: Broke the code because the integral divergent
Is this correct? What would be a better solution?

**Comment by fkiraly** [comment]
I think it should simply return `Inf` since that's the correct (analytical) answer.

If you are using a numerical approximator, I think it should return two warnings:
- one for the fact that you are using a numerical method
- one for the message where said method discovers that the integral diverges

in line with discussion in #7 ?

**Comment by RaphaelS1** [comment]
In this specific case we would have an analytic expression instead of numeric and yes it would return `Inf`. We currently implement the former suggested message. In regards to the second one, this would involve catching the error and converting it to a message, which is do-able but I think instead we should use (my) `stopwarn` function that lets the user pick between whether it should throw an error or warning (default)
